### PR TITLE
#161348794 Password reset

### PR DESCRIPTION
**Pull request by judeinno**
#### What does this PR do?
- Password reset.
- Refactor tests to use basetest file.
- Update email sending mechanism to use sendgrid API.

#### Description of Task to be completed?
Get the following endpoints working.
`POST api/user/reset_password`
`PUT user/reset_password/<reset_password_token>`

#### How should this be manually tested?
- Given the user forgets or wants to reset his/her password.
- In post man using the url:POST-api/user/reset_password, he/she enters the email address as the payload below.
````
{ "email" : "email-address" }
````
- Then an email is set to the given email address with the url: PUT-user/reset_password/<reset_password_token>
- Again in postman using the url in the email PUT the new password using the payload;
````
{
    "new_password": "jude1234*",
    "confirm_password": "jude1234*"
}
````
- After try out the new password on login to confirm that it has been reset.

#### What are the relevant pivotal tracker stories?
[#161348794](https://www.pivotaltracker.com/story/show/161348794)

### CODE REVIEW

**Review by emugaya — CHANGES_REQUESTED** [review]
Create a separate lib for sending an email that can be reused across the application as discussed on Friday. I am not merging this PR until that has been done.

**Review by brucemakallan — COMMENTED** [review]
Thanks for adding the BaseTest class. I had mentioned how our Tests had lots of repetition and you fixed it. Your application on Heroku requires a *SEND_GRID_API_KEY*. Please add that.

**Comment by dnuwa** [comment]
you did well refactoring the tests.

**Review by brucemakallan — APPROVED** [review]

**Review by dnuwa — APPROVED** [review]

**Review by RachaelNantale — APPROVED** [review]

**Review by emugaya — APPROVED** [review]

**Review by RachaelNantale — APPROVED** [review]
Good work with the  refactoring the code to PEP8 standards

**Pull request merged**
